name: eeppr
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.7=py39h9128911_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py39hd77b12b_8
  - ca-certificates=2024.7.2=haa95532_0
  - certifi=2024.7.4=py39haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py39haa95532_0
  - cuda-cccl=12.6.37=0
  - cuda-cccl_win-64=12.6.37=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.37=0
  - cuda-opencl-dev=12.6.37=0
  - cuda-profiler-api=12.6.37=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - filelock=3.13.1=py39haa95532_0
  - fonttools=4.51.0=py39h2bbff1b_0
  - freetype=2.12.1=ha860e81_0
  - gmpy2=2.1.2=py39h7f96b67_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.4=py39haa95532_0
  - jpeg=9e=h827c3e9_3
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.7.37=0
  - libcurand-dev=10.3.7.37=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py39h2bbff1b_0
  - matplotlib=3.4.3=py39haa95532_0
  - matplotlib-base=3.4.3=py39h49ac443_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.8=py39h2bbff1b_0
  - mkl_random=1.2.4=py39h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py39haa95532_0
  - networkx=3.2.1=py39haa95532_0
  - numexpr=2.8.7=py39h2cd9be0_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.14=h827c3e9_0
  - packaging=24.1=py39haa95532_0
  - pandas=1.5.3=py39hf11a4ad_0
  - pillow=10.4.0=py39h827c3e9_0
  - pip=24.0=py39haa95532_0
  - ply=3.11=py39haa95532_0
  - pybind11-abi=5=hd3eb1b0_0
  - pyparsing=3.0.9=py39haa95532_0
  - pyqt=5.15.10=py39hd77b12b_0
  - pyqt5-sip=12.13.0=py39h2bbff1b_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.19=h1aa4202_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - pytorch=2.4.0=py3.9_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py39haa95532_0
  - pyyaml=6.0.1=py39h2bbff1b_0
  - qt-main=5.15.2=h19c9488_10
  - requests=2.32.3=py39haa95532_0
  - scipy=1.13.1=py39h8640f81_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - setuptools=72.1.0=py39haa95532_0
  - sip=6.7.12=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - sympy=1.12=py39haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - tomli=2.0.1=py39haa95532_0
  - tornado=6.4.1=py39h827c3e9_0
  - tqdm=4.63.0=pyhd3eb1b0_0
  - typing_extensions=4.11.0=py39haa95532_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py39h2bbff1b_0
  - urllib3=2.2.2=py39haa95532_0
  - vc=14.2=h2eaa2aa_4
  - vs2015_runtime=14.29.30133=h43f2093_4
  - wheel=0.43.0=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.5=hd43e919_2
  - pip:
      - beautifulsoup4==4.12.3
      - einops==0.8.0
      - gdown==5.2.0
      - h5py==3.7.0
      - llvmlite==0.43.0
      - numba==0.60.0
      - soupsieve==2.5
      - sparse==0.15.4
      - torchaudio==2.4.0
      - torchvision==0.19.0